#!/bin/bash
# 这是一个自动生成的同步脚本，用于将修改应用到新的 OpenWrt 源码根目录

echo "正在应用补丁文件到当前项目..."
cp -r -f "package/luci-app-airoha-npu" "../package/"
mkdir -p "../package/kernel/linux/files"
cp -f "package/kernel/linux/files/sysctl-nf-conntrack.conf" "../package/kernel/linux/files/sysctl-nf-conntrack.conf"
mkdir -p "../package/kernel/linux/modules"
cp -f "package/kernel/linux/modules/netdevices.mk" "../package/kernel/linux/modules/netdevices.mk"
mkdir -p "../package/base-files/files/etc/uci-defaults"
cp -f "package/base-files/files/etc/uci-defaults/99_fix-airoha-mac" "../package/base-files/files/etc/uci-defaults/99_fix-airoha-mac"
mkdir -p "../package/base-files/files/etc"
cp -f "package/base-files/files/etc/sysctl.conf" "../package/base-files/files/etc/sysctl.conf"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/config-6.12" "../target/linux/airoha/an7581/config-6.12"
mkdir -p "../target/linux/airoha/an7581/base-files/etc/board.d"
cp -f "target/linux/airoha/an7581/base-files/etc/board.d/02_network" "../target/linux/airoha/an7581/base-files/etc/board.d/02_network"
mkdir -p "../target/linux/airoha/an7581/base-files/lib/upgrade"
cp -f "target/linux/airoha/an7581/base-files/lib/upgrade/platform.sh" "../target/linux/airoha/an7581/base-files/lib/upgrade/platform.sh"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/target.mk" "../target/linux/airoha/an7581/target.mk"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-nowifi.dtsi" "../target/linux/airoha/dts/an7581-nowifi.dtsi"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-xg-040g-md.dts" "../target/linux/airoha/dts/an7581-xg-040g-md.dts"
mkdir -p "../target/linux/airoha/image"
cp -f "target/linux/airoha/image/an7581.mk" "../target/linux/airoha/image/an7581.mk"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch" "../target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch" "../target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch" "../target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch" "../target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch" "../target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch"
mkdir -p "../target/linux/generic/hack-6.12"
cp -f "target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch" "../target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch" "../target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch"
echo "补丁应用完成！"
