#!/bin/bash
# 这是一个自动生成的同步脚本，用于将修改应用到新的 OpenWrt 源码根目录

echo "正在应用补丁文件到当前项目..."
mkdir -p "../."
cp -f "feeds.conf.default" "../feeds.conf.default"
mkdir -p "../package/base-files/files/etc"
cp -f "package/base-files/files/etc/sysctl.conf" "../package/base-files/files/etc/sysctl.conf"
mkdir -p "../package/kernel/linux/files"
cp -f "package/kernel/linux/files/sysctl-nf-conntrack.conf" "../package/kernel/linux/files/sysctl-nf-conntrack.conf"
mkdir -p "../package/kernel/linux/modules"
cp -f "package/kernel/linux/modules/netdevices.mk" "../package/kernel/linux/modules/netdevices.mk"
mkdir -p "../target/linux/airoha"
cp -f "target/linux/airoha/Makefile" "../target/linux/airoha/Makefile"
mkdir -p "../target/linux/airoha/an7581/base-files/etc/board.d"
cp -f "target/linux/airoha/an7581/base-files/etc/board.d/02_network" "../target/linux/airoha/an7581/base-files/etc/board.d/02_network"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/config-6.12" "../target/linux/airoha/an7581/config-6.12"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/target.mk" "../target/linux/airoha/an7581/target.mk"
mkdir -p "../target/linux/airoha/image"
cp -f "target/linux/airoha/image/an7581.mk" "../target/linux/airoha/image/an7581.mk"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch" "../target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch" "../target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch"
mkdir -p "../target/linux/generic/hack-6.12"
cp -f "target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch" "../target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch"
mkdir -p "../package/base-files/files/etc/uci-defaults"
cp -f "package/base-files/files/etc/uci-defaults/99_fix-airoha-mac" "../package/base-files/files/etc/uci-defaults/99_fix-airoha-mac"
mkdir -p "../package"
cp -rf "package/luci-app-airoha-npu/" "../package/"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-evb-emmc.dts" "../target/linux/airoha/dts/an7581-evb-emmc.dts"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-nowifi.dtsi" "../target/linux/airoha/dts/an7581-nowifi.dtsi"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-xg-040g-md.dts" "../target/linux/airoha/dts/an7581-xg-040g-md.dts"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch" "../target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/180-v7.1-net-airoha-Fix-memory-leak-in-airoha_qdma_rx_process.patch" "../target/linux/airoha/patches-6.12/180-v7.1-net-airoha-Fix-memory-leak-in-airoha_qdma_rx_process.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch" "../target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch" "../target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/910-02-usb-pcie.patch" "../target/linux/airoha/patches-6.12/910-02-usb-pcie.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch" "../target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch" "../target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-01-net-export-__dev_fill_forward_path-and-br_fdb_find_rcu.patch" "../target/linux/generic/pending-6.12/675-01-net-export-__dev_fill_forward_path-and-br_fdb_find_rcu.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-02-nft_flow_offload-add-bridging-support.patch" "../target/linux/generic/pending-6.12/675-02-nft_flow_offload-add-bridging-support.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-04-nft_flow_offload-add-vlan-passthrough-support.patch" "../target/linux/generic/pending-6.12/675-04-nft_flow_offload-add-vlan-passthrough-support.patch"
echo "补丁应用完成！"
