#!/bin/bash
# 这是一个自动生成的同步脚本，用于将修改应用到新的 OpenWrt 源码根目录

echo "正在应用补丁文件到当前项目..."
cp -r -f "package/luci-app-airoha-npu" "../package/"
rm -f ../target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch ../package/boot/uboot-mediatek/patches/342-mtd-spinand-Support-fmsh.patch ../target/linux/generic/backport-6.12/401-01-v6.18-mtd-spinand-add-support-for-FudanMicro-FM25S01A.patch ../target/linux/generic/backport-6.12/401-02-v6.18-mtd-spinand-fmsh-remove-QE-bit-for-FM25S01A-flash.patch
mkdir -p "../package/boot/uboot-mediatek/patches"
cp -f "package/boot/uboot-mediatek/patches/100-20-mtd-spi-nand-add-support-for-FudanMicro-chips.patch" "../package/boot/uboot-mediatek/patches/100-20-mtd-spi-nand-add-support-for-FudanMicro-chips.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/401-v6.17-mtd-spinand-add-support-for-FudanMicro-FM25S01A.patch" "../target/linux/generic/backport-6.12/401-v6.17-mtd-spinand-add-support-for-FudanMicro-FM25S01A.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/404-v6.19-mtd-spinand-fmsh-remove-QE-bit-for-FM25S01A-flash.patch" "../target/linux/generic/backport-6.12/404-v6.19-mtd-spinand-fmsh-remove-QE-bit-for-FM25S01A-flash.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/435-v6.19-mtd-spinand-add-support-for-FudanMicro-FM25S01BI3.patch" "../target/linux/generic/backport-6.12/435-v6.19-mtd-spinand-add-support-for-FudanMicro-FM25S01BI3.patch"
mkdir -p "../package/boot/uboot-tools/uboot-envtools/files"
cp -f "package/boot/uboot-tools/uboot-envtools/files/mediatek_filogic" "../package/boot/uboot-tools/uboot-envtools/files/mediatek_filogic"
mkdir -p "../package/kernel/linux/modules"
cp -f "package/kernel/linux/modules/netdevices.mk" "../package/kernel/linux/modules/netdevices.mk"
mkdir -p "../target/linux/airoha/an7581/base-files/etc/board.d"
cp -f "target/linux/airoha/an7581/base-files/etc/board.d/02_network" "../target/linux/airoha/an7581/base-files/etc/board.d/02_network"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/config-6.12" "../target/linux/airoha/an7581/config-6.12"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/target.mk" "../target/linux/airoha/an7581/target.mk"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-bell_xg-040g-md.dts" "../target/linux/airoha/dts/an7581-bell_xg-040g-md.dts"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-nowifi.dtsi" "../target/linux/airoha/dts/an7581-nowifi.dtsi"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581.dtsi" "../target/linux/airoha/dts/an7581.dtsi"
mkdir -p "../target/linux/airoha/image"
cp -f "target/linux/airoha/image/an7581.mk" "../target/linux/airoha/image/an7581.mk"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch" "../target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch" "../target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/901-snand-mtk-bmt-support.patch" "../target/linux/airoha/patches-6.12/901-snand-mtk-bmt-support.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch" "../target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch" "../target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/434-v6.19-mtd-spinand-esmt-add-support-for-F50L1G41LC.patch" "../target/linux/generic/backport-6.12/434-v6.19-mtd-spinand-esmt-add-support-for-F50L1G41LC.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch" "../target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/499-mtd-spinand-FudanMicro-FM25G02B.patch" "../target/linux/generic/pending-6.12/499-mtd-spinand-FudanMicro-FM25G02B.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/600-mtd-spinand-add-skyhigh-robust-read-workaround.patch" "../target/linux/generic/pending-6.12/600-mtd-spinand-add-skyhigh-robust-read-workaround.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/121-hack-spi-nand-1b-bbm.patch" "../target/linux/mediatek/patches-6.12/121-hack-spi-nand-1b-bbm.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/330-snand-mtk-bmt-support.patch" "../target/linux/mediatek/patches-6.12/330-snand-mtk-bmt-support.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/340-mtd-spinand-Add-support-for-the-Fidelix-FM35X1GA.patch" "../target/linux/mediatek/patches-6.12/340-mtd-spinand-Add-support-for-the-Fidelix-FM35X1GA.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/435-drivers-mtd-spinand-Add-calibration-support-for-spin.patch" "../target/linux/mediatek/patches-6.12/435-drivers-mtd-spinand-Add-calibration-support-for-spin.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/436-drivers-mtd-spi-nor-Add-calibration-support-for-spi-.patch" "../target/linux/mediatek/patches-6.12/436-drivers-mtd-spi-nor-Add-calibration-support-for-spi-.patch"
mkdir -p "../target/linux/mediatek/patches-6.12"
cp -f "target/linux/mediatek/patches-6.12/960-asus-hack-u-boot-ignore-mtdparts.patch" "../target/linux/mediatek/patches-6.12/960-asus-hack-u-boot-ignore-mtdparts.patch"
echo "补丁应用完成！"
