#!/bin/bash
# 这是一个自动生成的同步脚本，用于将修改应用到新的 OpenWrt 源码根目录

echo "正在应用补丁文件到当前项目..."

# 首先删除已被移除的文件
rm -f "../target/linux/airoha/patches-6.12/116-02-net-airoha-deassert-XSI-line-on-hw-init.patch"
rm -f "../target/linux/airoha/patches-6.12/116-03-net-airoha-add-reference-for-SPORT-GDM4-in-qdma_get_.patch"
rm -f "../target/linux/airoha/patches-6.12/116-06-net-airoha-add-initial-fixup-for-GDM3-4-port-support.patch"
rm -f "../target/linux/airoha/patches-6.12/116-07-airoha-ethernet-drop-xsi-mac-reset.patch"
rm -f "../target/linux/airoha/patches-6.12/116-08-net-phylink-add-.pcs_link_down-PCS-OP.patch"
rm -f "../target/linux/airoha/patches-6.12/116-09-net-pcs-airoha-add-PCS-driver-for-Airoha-SoC.patch"
rm -f "../target/linux/airoha/patches-6.12/116-10-net-airoha-add-phylink-support-for-GDM2-4.patch"
rm -f "../target/linux/airoha/patches-6.12/123-02-ASoC-airoha-Add-AFE-and-I2S-driver-for-Airoha-AN7581.patch"
rm -f "../target/linux/airoha/patches-6.12/610-v7.0-net-phy-mediatek-enable-interrupts-on-AN7581.patch"
rm -f "../target/linux/airoha/patches-6.12/611-v7.0-net-airoha-implement-get_link_ksettings.patch"
rm -f "../target/linux/airoha/patches-6.12/910-01-v7.0-net-airoha-npu-Init-BA-memory-region-if.patch"
rm -f "../target/linux/airoha/patches-6.12/910-02-v7.0-net-airoha-npu-Add-the-capability-to-read-firmware-n.patch"

echo "正在复制更新后的文件..."
mkdir -p "../."
cp -f "feeds.conf.default" "../feeds.conf.default"
mkdir -p "../package/base-files/files/etc"
cp -f "package/base-files/files/etc/sysctl.conf" "../package/base-files/files/etc/sysctl.conf"
mkdir -p "../package/kernel/linux/files"
cp -f "package/kernel/linux/files/sysctl-nf-conntrack.conf" "../package/kernel/linux/files/sysctl-nf-conntrack.conf"
mkdir -p "../package/kernel/linux/modules"
cp -f "package/kernel/linux/modules/netdevices.mk" "../package/kernel/linux/modules/netdevices.mk"
mkdir -p "../target/linux/airoha"
cp -f "target/linux/airoha/Makefile" "../target/linux/airoha/Makefile"
mkdir -p "../target/linux/airoha/an7581/base-files/etc/board.d"
cp -f "target/linux/airoha/an7581/base-files/etc/board.d/02_network" "../target/linux/airoha/an7581/base-files/etc/board.d/02_network"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/config-6.12" "../target/linux/airoha/an7581/config-6.12"
mkdir -p "../target/linux/airoha/an7581"
cp -f "target/linux/airoha/an7581/target.mk" "../target/linux/airoha/an7581/target.mk"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-evb-emmc.dts" "../target/linux/airoha/dts/an7581-evb-emmc.dts"
mkdir -p "../target/linux/airoha/image"
cp -f "target/linux/airoha/image/an7581.mk" "../target/linux/airoha/image/an7581.mk"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/034-01-v6.13-pinctrl-airoha-Add-support-for-EN7581-SoC.patch" "../target/linux/airoha/patches-6.12/034-01-v6.13-pinctrl-airoha-Add-support-for-EN7581-SoC.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch" "../target/linux/airoha/patches-6.12/039-v6.14-cpufreq-airoha-Add-EN7581-CPUFreq-SMCCC-driver.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch" "../target/linux/airoha/patches-6.12/040-v6.14-pmdomain-airoha-Add-Airoha-CPU-PM-Domain-support.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/600-10-clk-en7523-add-support-for-Airoha-AN7583-clock.patch" "../target/linux/airoha/patches-6.12/600-10-clk-en7523-add-support-for-Airoha-AN7583-clock.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/606-net-airoha-disable-external-phy-code-if-PCS_AIROHA-i.patch" "../target/linux/airoha/patches-6.12/606-net-airoha-disable-external-phy-code-if-PCS_AIROHA-i.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/901-snand-mtk-bmt-support.patch" "../target/linux/airoha/patches-6.12/901-snand-mtk-bmt-support.patch"
mkdir -p "../target/linux/generic/hack-6.12"
cp -f "target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch" "../target/linux/generic/hack-6.12/400-mtd-spinand-Support-fmsh.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch" "../target/linux/generic/pending-6.12/487-mtd-spinand-Add-support-for-Etron-EM73D044VCx.patch"
mkdir -p "../package/base-files/files/etc/uci-defaults"
cp -f "package/base-files/files/etc/uci-defaults/99_fix-airoha-mac" "../package/base-files/files/etc/uci-defaults/99_fix-airoha-mac"
mkdir -p "../package"
cp -rf "package/luci-app-airoha-npu/" "../package/"
mkdir -p "../target/linux/airoha/an7581/base-files"
cp -rf "target/linux/airoha/an7581/base-files/lib/" "../target/linux/airoha/an7581/base-files/"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-nowifi.dtsi" "../target/linux/airoha/dts/an7581-nowifi.dtsi"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-npu-mt7996.dtsi" "../target/linux/airoha/dts/an7581-npu-mt7996.dtsi"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-w1700k-ubi.dts" "../target/linux/airoha/dts/an7581-w1700k-ubi.dts"
mkdir -p "../target/linux/airoha/dts"
cp -f "target/linux/airoha/dts/an7581-xg-040g-md.dts" "../target/linux/airoha/dts/an7581-xg-040g-md.dts"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/114-v7.0-hwrng-airoha-set-rng-quality-to-900.patch" "../target/linux/airoha/patches-6.12/114-v7.0-hwrng-airoha-set-rng-quality-to-900.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/115-v7.0-net-airoha-Fix-npu-rx-DMA-definitions.patch" "../target/linux/airoha/patches-6.12/115-v7.0-net-airoha-Fix-npu-rx-DMA-definitions.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/116-v6.19-net-airoha-Move-net_devs-registration-in-a-dedicated.patch" "../target/linux/airoha/patches-6.12/116-v6.19-net-airoha-Move-net_devs-registration-in-a-dedicated.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch" "../target/linux/airoha/patches-6.12/117-03-airoha_npu_eagle_add_ser.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/117-v7.0-net-airoha-Use-gdm-port-enum-value-whenever-possible.patch" "../target/linux/airoha/patches-6.12/117-v7.0-net-airoha-Use-gdm-port-enum-value-whenever-possible.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/118-v7.0-net-airoha-npu-Dump-fw-version-during-probe.patch" "../target/linux/airoha/patches-6.12/118-v7.0-net-airoha-npu-Dump-fw-version-during-probe.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/119-v6.19-net-airoha-Fix-schedule-while-atomic-in-airoha_ppe_d.patch" "../target/linux/airoha/patches-6.12/119-v6.19-net-airoha-Fix-schedule-while-atomic-in-airoha_ppe_d.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/120-v7.0-net-airoha-implement-get_link_ksettings.patch" "../target/linux/airoha/patches-6.12/120-v7.0-net-airoha-implement-get_link_ksettings.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/121-v7.0-net-airoha-npu-Init-BA-memory-region-if-provided-via.patch" "../target/linux/airoha/patches-6.12/121-v7.0-net-airoha-npu-Init-BA-memory-region-if-provided-via.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/122-v7.0-net-airoha_eth-increase-max-MTU-to-9220-for-DSA-jumb.patch" "../target/linux/airoha/patches-6.12/122-v7.0-net-airoha_eth-increase-max-MTU-to-9220-for-DSA-jumb.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/123-v7.0-net-airoha-npu-Add-the-capability-to-read-firmware-n.patch" "../target/linux/airoha/patches-6.12/123-v7.0-net-airoha-npu-Add-the-capability-to-read-firmware-n.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/124-v7.1-net-airoha-fix-typo-in-function-name.patch" "../target/linux/airoha/patches-6.12/124-v7.1-net-airoha-fix-typo-in-function-name.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/125-v7.1-net-airoha-Rely-__field_prep-for-non-constant-masks.patch" "../target/linux/airoha/patches-6.12/125-v7.1-net-airoha-Rely-__field_prep-for-non-constant-masks.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/126-v7.1-net-airoha-Make-flow-control-source-port-mapping-dep.patch" "../target/linux/airoha/patches-6.12/126-v7.1-net-airoha-Make-flow-control-source-port-mapping-dep.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/127-v7.1-net-airoha-Move-GDM-forward-port-configuration-in-nd.patch" "../target/linux/airoha/patches-6.12/127-v7.1-net-airoha-Move-GDM-forward-port-configuration-in-nd.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/129-v7.1-net-airoha-select-QDMA-block-according-LAN-WAN-confi.patch" "../target/linux/airoha/patches-6.12/129-v7.1-net-airoha-select-QDMA-block-according-LAN-WAN-confi.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/130-v7.0-net-airoha-Fix-typo-in-airoha_ppe_setup_tc_block_cb-.patch" "../target/linux/airoha/patches-6.12/130-v7.0-net-airoha-Fix-typo-in-airoha_ppe_setup_tc_block_cb-.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/131-v7.0-net-phy-mediatek-enable-interrupts-on-AN7581.patch" "../target/linux/airoha/patches-6.12/131-v7.0-net-phy-mediatek-enable-interrupts-on-AN7581.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/132-v7.1-net-airoha-Reset-PPE-default-cput-port-in-airoha_ppe.patch" "../target/linux/airoha/patches-6.12/132-v7.1-net-airoha-Reset-PPE-default-cput-port-in-airoha_ppe.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/133-v7.1-net-airoha-Rework-the-code-flow-in-airoha_remove-and.patch" "../target/linux/airoha/patches-6.12/133-v7.1-net-airoha-Rework-the-code-flow-in-airoha_remove-and.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/134-v7.1-net-airoha-Delay-offloading-until-all-net_devices-ar.patch" "../target/linux/airoha/patches-6.12/134-v7.1-net-airoha-Delay-offloading-until-all-net_devices-ar.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/135-v7.1-net-airoha-Add-missing-cleanup-bits-in-airoha_qdma_c.patch" "../target/linux/airoha/patches-6.12/135-v7.1-net-airoha-Add-missing-cleanup-bits-in-airoha_qdma_c.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/180-v7.1-net-airoha-Fix-memory-leak-in-airoha_qdma_rx_process.patch" "../target/linux/airoha/patches-6.12/180-v7.1-net-airoha-Fix-memory-leak-in-airoha_qdma_rx_process.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/200-02-ASoC-airoha-Add-AFE-and-I2S-driver-for-Airoha-AN7581.patch" "../target/linux/airoha/patches-6.12/200-02-ASoC-airoha-Add-AFE-and-I2S-driver-for-Airoha-AN7581.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/202-pinctrl-airoha-permit-GPIO43-46-for-PHY-LED0.patch" "../target/linux/airoha/patches-6.12/202-pinctrl-airoha-permit-GPIO43-46-for-PHY-LED0.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-02-net-airoha-deassert-XSI-line-on-hw-init.patch" "../target/linux/airoha/patches-6.12/310-02-net-airoha-deassert-XSI-line-on-hw-init.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-03-net-airoha-add-reference-for-SPORT-GDM4-in-qdma_get_.patch" "../target/linux/airoha/patches-6.12/310-03-net-airoha-add-reference-for-SPORT-GDM4-in-qdma_get_.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-06-net-airoha-add-initial-fixup-for-GDM3-4-port-support.patch" "../target/linux/airoha/patches-6.12/310-06-net-airoha-add-initial-fixup-for-GDM3-4-port-support.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-07-airoha-ethernet-drop-xsi-mac-reset.patch" "../target/linux/airoha/patches-6.12/310-07-airoha-ethernet-drop-xsi-mac-reset.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-08-net-phylink-add-.pcs_link_down-PCS-OP.patch" "../target/linux/airoha/patches-6.12/310-08-net-phylink-add-.pcs_link_down-PCS-OP.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-09-net-pcs-airoha-add-PCS-driver-for-Airoha-SoC.patch" "../target/linux/airoha/patches-6.12/310-09-net-pcs-airoha-add-PCS-driver-for-Airoha-SoC.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/310-10-net-airoha-add-phylink-support-for-GDM2-4.patch" "../target/linux/airoha/patches-6.12/310-10-net-airoha-add-phylink-support-for-GDM2-4.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch" "../target/linux/airoha/patches-6.12/620-net-pcs-airoha-fix-USXGMII-rate-adaptation-on-speed.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch" "../target/linux/airoha/patches-6.12/621-net-pcs-airoha-AN7581-add-global-digital-reset-for.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/910-02-usb-pcie.patch" "../target/linux/airoha/patches-6.12/910-02-usb-pcie.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch" "../target/linux/airoha/patches-6.12/992-mtd-spinand-add-skyhigh-robust-read-workaround.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch" "../target/linux/airoha/patches-6.12/999-dsa-01-add-mt7531-netlink-support.patch"
mkdir -p "../target/linux/airoha/patches-6.12"
cp -f "target/linux/airoha/patches-6.12/999-fix-airoha-missing-header.patch" "../target/linux/airoha/patches-6.12/999-fix-airoha-missing-header.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch" "../target/linux/generic/backport-6.12/430-v6.14-mtd-spinand-Introduce-a-way-to-avoid-raw-access.patch"
mkdir -p "../target/linux/generic/backport-6.12"
cp -f "target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch" "../target/linux/generic/backport-6.12/431-v6.14-mtd-spinand-Add-support-for-SkyHigh-S35ML-3-family.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-01-net-export-__dev_fill_forward_path-and-br_fdb_find_rcu.patch" "../target/linux/generic/pending-6.12/675-01-net-export-__dev_fill_forward_path-and-br_fdb_find_rcu.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-02-nft_flow_offload-add-bridging-support.patch" "../target/linux/generic/pending-6.12/675-02-nft_flow_offload-add-bridging-support.patch"
mkdir -p "../target/linux/generic/pending-6.12"
cp -f "target/linux/generic/pending-6.12/675-04-nft_flow_offload-add-vlan-passthrough-support.patch" "../target/linux/generic/pending-6.12/675-04-nft_flow_offload-add-vlan-passthrough-support.patch"
echo "补丁应用完成！"
